spring:
  application:
    name: eureka-client-customer
server:
  port: 2101

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:1001/eureka/

logging:
  file: ${spring.application.name}.log