spring:
  application:
    name: eureka-client-consumer-ribbon
server:
  port: 2102

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:1001/eureka/

logging:
  file: ${spring.application.name}.log